//AUTH 
export const LOGIN_START = "LOGIN_START"
export const LOGIN_FAILED = "LOGIN_FAILED"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const SET_USERNAME = "SET_USERNAME"
export const SET_ID = "SET_ID"
export const SET_ROLE = "SET_ROLE"
export const LOGOUT = "LOGOUT"


//BLOG
export const SET_BLOG_LIST = "SET_BLOG_LIST"
export const SET_BLOG_ERRORS = "SET_BLOG_ERRORS"
export const SET_BLOG_LOADING = "SET_BLOG_LOADING"
export const SET_BLOG = "SET_BLOG"

//GALERIE 
export const SET_ALBUM_LIST = "SET_ALBUM_LIST"
export const SET_ALBUM_LOADING = "SET_ALBUM_LOADING"
export const SET_ALBUM_ERROR = "SET_ALBUM_ERROR"
export const SET_ALBUM_GALERIE = "SET_ALBUM_GALERIE"


//AGENDA
export const SET_AGENDA_LIST = "SET_AGENDA_LIST"
export const SET_AGENDA_ERRORS = "SET_AGENDA_ERRORS"
export const SET_AGENDA_LOADING = "SET_AGENDA_LOADING"
export const SET_AGENDA = "SET_AGENDA"

//ACTIVITE
export const SET_ACTIVITE_LIST = "SET_ACTIVITE_LIST"
export const SET_ACTIVITE_LOADING = "SET_ACTIVITE_LOADING"
export const SET_ACTIVITE_ERRORS = "SET_ACTIVITE_ERRORS"
export const SET_ACTIVITE = "SET_ACTIVITE"
